import type { Job } from './types'; import { enrichForProfile } from './profile';
const now=new Date().toISOString();
const rows:Job[]=[
 {id:'seed-hap-denali-dish',agency:'OEG',employer:'HAP Denali Princess Wilderness Lodge',season:'Summer 2027',state:'Alaska',city:'Denali',position:'Dish Steward',wageMin:17,wageMax:17,wageText:'$17/hr',housingWeekly:119,housingText:'$119/week',mealsIncluded:true,mealsText:'รวม 3 มื้อ',availableSlots:0,status:'FULL',startText:'11–18 May 2027',endText:'7 Sep 2027',sourceUrl:'https://www.oeg.co.th/work-and-travel-usa/detail/264',lastSeenAt:now},
 {id:'seed-hap-denali-prep',agency:'OEG',employer:'HAP Denali Princess Wilderness Lodge',season:'Summer 2027',state:'Alaska',city:'Denali',position:'Prep Cook',wageMin:17,wageMax:17,wageText:'$17/hr',housingWeekly:119,housingText:'$119/week',mealsIncluded:true,mealsText:'รวม 3 มื้อ',availableSlots:0,status:'FULL',sourceUrl:'https://www.oeg.co.th/work-and-travel-usa/detail/264',lastSeenAt:now},
 {id:'seed-glacier-pursuit-prep',agency:'OEG',employer:'Glacier Park by Pursuit – Glacier Park Lodge',season:'Summer 2027',state:'Montana',city:'East Glacier Park',position:'Cook 1 - Prep Cook',wageMin:16,wageMax:16,wageText:'$16/hr',housingWeekly:101.5,housingText:'$101.50/week',mealsIncluded:true,mealsText:'3 meals/day',availableSlots:0,status:'FULL',sourceUrl:'https://oeg.co.th/work-and-travel-usa/detail/28',lastSeenAt:now},
 {id:'seed-yellowstone',agency:'ACADEX',employer:'Xanterra Yellowstone National Park',season:'Summer 2027',state:'Wyoming',city:'Yellowstone National Park',position:'Hospitality Crew / Kitchen Crew request',wageMin:15.7,wageMax:15.7,wageText:'$15.70/hr',housingWeekly:120.05,housingText:'$120.05/week',mealsIncluded:true,mealsText:'3 meals/day',hoursMin:32,hoursMax:40,hoursText:'32–40 hr/week',availableSlots:0,status:'FULL',sourceUrl:'https://www.acadexthailand.com/location/xanterra-yellowstone-national-park-wyoming-summer-2027-group-x/',lastSeenAt:now},
 {id:'seed-grand-teton',agency:'ACADEX',employer:'Grand Teton Lodge',season:'Summer 2027',state:'Wyoming',city:'Moran/Moose/Jackson',position:'Kitchen Workers / Entry Level Cooks / Dishwashers',wageMin:17.75,wageMax:22,wageText:'$17.75–22/hr',housingWeekly:0,housingText:'2026: Free housing; 2027 TBA',mealsIncluded:true,mealsText:'2026 meal plan $115/week',hoursMin:32,hoursMax:40,hoursText:'32–40 hr/week',availableSlots:0,status:'FULL',sourceUrl:'https://www.acadexthailand.com/location/grand-teton-lodge-wyoming-summer-2027-group-a/',lastSeenAt:now}
];
export const seedJobs=rows.map(enrichForProfile);
